### ISSUE TITLE
Tags in https://schulung3.geomar.de/

### ISSUE THREAD

**Issue by PerlisChatton** [geomar-od-lagrange/papermill-demo#2]
Sorry, this is a super basic question, but I have been trying to find the cell tags in jupyterlab from the workshop and I had tried to follow the path: View, Cell Toolbar, and then Tags, but there's no cell toolbar option, so I wonder if there is another way to access to it.

Thank you for your hep

**Comment by willirath** [comment]
The papermill docs are a little misleading here. The way you quote is for the classical notebook interface. For JupyterLab (which is on the workshop machine), you'll need to follow ["JupyterLab < 2.0" from the papermill documentation](https://papermill.readthedocs.io/en/latest/usage-parameterize.html#id1).

**Comment by willirath** [comment]
See this screenshot: 
![image](https://user-images.githubusercontent.com/5700886/107539444-437e1d80-6bc5-11eb-870c-5ffebedd3593.png)

**Comment by PerlisChatton** [comment]
Thank you, it works and I understood how to use it with papermill.
